### ISSUE TITLE
Problems with requirements.txt

### ISSUE THREAD

**Issue by piotor87** [telegraphic/hickle#105]
I've been trying to build a docker with hickle but it keeps failing with this message:
```
pip3 install hickle
Collecting hickle
  Using cached https://files.pythonhosted.org/packages/71/b0/240b5eeb1b5d236e1709388bd0980f4edf15f18c52cf3415f6abebf5efc9/hickle-3.4.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v7qpr37t/hickle/setup.py", line 18, in <module>
        with open("requirements.txt", 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v7qpr37t/hickle/
```

I get the same error also trying to install the package locally.

**Comment by 1313e** [comment]
This problem was already fixed in #104, but that has not been released yet.

**Comment by 1313e** [comment]
@piotor87 I just checked, should be working properly now.

**Comment by piotor87** [comment]
It does! Great, thanks!
