### ISSUE TITLE
Can't dump long integers

### ISSUE THREAD

**Issue by cdcapano** [telegraphic/hickle#113]
If I try to dump an object that contains a long integer, I get an OSError. A simple example:
```
>>> import hickle
>>> num = 123456789101112131415
>>> hickle.dump(num, 'foo.hdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cdcapano/.virtualenvs/python36-pycbc/lib/python3.6/site-packages/hickle/hickle.py", line 294, in dump
    _dump(py_obj, h_root_group, **kwargs)
  File "/Users/cdcapano/.virtualenvs/python36-pycbc/lib/python3.6/site-packages/hickle/hickle.py", line 253, in _dump
    create_hkl_dataset(py_obj, h_group, call_id, **kwargs)
  File "/Users/cdcapano/.virtualenvs/python36-pycbc/lib/python3.6/site-packages/hickle/hickle.py", line 345, in create_hkl_dataset
    create_dataset(py_obj, h_group, call_id, **kwargs)
  File "/Users/cdcapano/.virtualenvs/python36-pycbc/lib/python3.6/site-packages/hickle/loaders/load_python3.py", line 85, in create_python_dtype_dataset
    dtype=type(py_obj))     #, **kwargs)
  File "/Users/cdcapano/.virtualenvs/python36-pycbc/lib/python3.6/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/Users/cdcapano/.virtualenvs/python36-pycbc/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 170, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't write data (no appropriate function for conversion path)
```

I've tried this with both python 3.6 and 2.7. Interestingly, it only happens when the integer exceeds 20 digits. Just removing a single integer from the above works, even though the number is a long (in python 2.7):
```
>>> num = 12345678910111213141
>>> hickle.dump(num, 'foo.hdf')
```

**Comment by 1313e** [comment]
I just tried this, and it has nothing to do with the number of digits.
For example, using `int('1'*20)` (20 ones) will work, but using `int('9'*20)` (20 nines) will not.
The reason for that is because the maximum value of an unsigned 64-bit integer is `2**64-1 = 18446744073709551615`, which contains 20 digits.
The example you were using with 20 digits is about two-thirds of that and therefore works perfectly fine.
You can also check this for yourself, as attempting to save `-int('1'*20)` (minus 20 ones) to HDF5 will not work either, because the maximum value of an signed 64-bit integer is `2**63-1 = 9223372036854775807` which has 19 digits.

As any number higher than that cannot be stored in an unsigned 64-bit integer, it cannot be stored in HDF5 either.
However, Python can use integers of any value, as it uses arbitrary-precision integers (nicely explained [here](https://rushter.com/blog/python-integer-implementation/)).
Instead of saving an integer as a single value, Python uses integer arrays to store the value of an integer if it exceeds the precision of a single one.

It would theoretically speaking be possible to store those integers in HDF5 as well, by simply saving them as a string instead of an integer, and converting them back to integers when read.
@telegraphic What do you think?

**Comment by telegraphic** [comment]
@cdcapano congratulations on finding a peculiar edge case! I agree this is bit length related:

```
num = 123456789101112131415
num.bit_length()
67
```

and would also agree that saving as a string is probably the way to go. I think we'd still want to store regular <64 bit integers as their native type. Tagging as pull-request-welcome, but I'm hoping to find time this week to check out the #112 pull request so may be able to tackle it at the same time.

**Comment by 1313e** [comment]
@telegraphic Well, I guess I will leave this one up to you then ;)
