### ISSUE TITLE
Segmentation fault issue

### ISSUE THREAD

**Issue by kleekaai** [telegraphic/hickle#151]
I am trying to use hickle(4.0.0) after installing it via pip in   python 3.6.8. After importing it and running the python file I am getting the following error. Can someone please look into this issue. Thanks

OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 20: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 385988 max
OpenBLAS blas_thread_init: pthread_create failed for thread 18 of 20: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 385988 max
OpenBLAS blas_thread_init: pthread_create failed for thread 19 of 20: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 385988 max
Traceback (most recent call last):
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ifis/ifis_semantic_similarity_lsi/train_lsi.py", line 10, in <module>
    from gensim import corpora, models
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/gensim/parsing/preprocessing.py", line 40, in <module>
    from gensim import utils
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/gensim/utils.py", line 38, in <module>
    import numpy as np
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/admin/pyVenv/lib64/python3.6/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "/home/admin/pyVenv/bin/python"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"

Segmentation fault

**Comment by 1313e** [comment]
This is not an issue with `hickle`, as it does not require OpenBLAS.
This seems to be an issue with NumPy.
