### ISSUE TITLE
please help me this bug，thank you

### ISSUE THREAD

**Issue by easewkx** [telegraphic/hickle#185]
Traceback (most recent call last):
  File "/home/wkx/.conda/envs/swinlstm/lib/python3.8/site-packages/hickle/hickle.py", line 569, in load
    raise FileError("HDF5-file does not have the proper attributes!")
hickle.hickle.FileError: HDF5-file does not have the proper attributes!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/wkx/OpenSTL-OpenSTLv0.3.0/openstl/datasets/dataloader_kitticaltech.py", line 200, in <module>
    load_data(batch_size=16,
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/wkx/OpenSTL-OpenSTLv0.3.0/openstl/datasets/dataloader_kitticaltech.py", line 166, in load_data
    train_data, train_idx = input_handle.load_data('train')
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/wkx/OpenSTL-OpenSTLv0.3.0/openstl/datasets/dataloader_kitticaltech.py", line 93, in load_data
    data = hkl.load(osp.join(kitti_root, 'X_' + mode + '.hkl'))
  File "/home/wkx/.conda/envs/swinlstm/lib/python3.8/site-packages/hickle/hickle.py", line 573, in load
    raise ValueError("Provided argument 'file_obj' does not appear to be a"
ValueError: Provided argument 'file_obj' does not appear to be a valid hickle file! (HDF5-file does not have the proper attributes!)

Process finished with exit code 1

**Comment by telegraphic** [comment]
closing as part of stale issue tidy-up. Hope you managed to find a solution.
