### ISSUE TITLE
Hickle dump doesn't work on simple case (Python 3.6)

### ISSUE THREAD

**Issue by antorsae** [telegraphic/hickle#63]
```
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hickle
/home/antor/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> print(hickle.__version__)
2.1.0
>>> dict = { }
>>> dict['foo'] ='bar'
>>> hickle.dump(dict, 'test.hkl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antor/miniconda3/lib/python3.6/site-packages/hickle.py", line 308, in dump
    h5f = file_opener(file_obj, mode, track_times)
  File "/home/antor/miniconda3/lib/python3.6/site-packages/hickle.py", line 148, in file_opener
    if isinstance(f, file):
NameError: name 'file' is not defined
```

**Comment by telegraphic** [comment]
Hi @antorsae , Python 3 support (see #8) is still only on the [dev branch](https://github.com/telegraphic/hickle/tree/dev). I'll push this to the master repository soon, it seems a lot of people are waiting on it! Closing this thread to keep Py3 discussion on #8.
