### ISSUE TITLE
IOError: Unable to open file when opening .hkl file from Directory

### ISSUE THREAD

**Issue by PyPatel** [telegraphic/hickle#64]
I have compiled my training data into hickle file with extension .hkl

    >>> import hickle as hkl
    >>> a = hkl.load('~/path/folder with file/X_train.hkl')

Above line is giving me the following error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 616, in load
        h5f = file_opener(fileobj)
      File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 154, in file_opener
        h5f = h5.File(filename, mode)
      File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
        fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
      File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
        fid = h5f.open(name, flags, fapl=fapl)
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
      File "h5py/h5f.pyx", line 78, in h5py.h5f.open
    IOError: Unable to open file (unable to open file: name = '~/path/folder with file/X_train.hkl', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I have tried using `'r'` with it, but same error is generated. What is the issue here? Is the file type not supported or way to load the file?

Please help. Thanks.

**Comment by telegraphic** [comment]
Hello @PyPatel -- this error is being thrown by `h5py`, not by `hickle` itself. If h5py can't open the file, then hickle can't either. 

Try just opening the file with:
```
import h5py
f = h5py.File('/path/to/file.hkl')
```

If the error is what it says it is (No such file or directory), it simply can't find the file. I would try: 1) replacing the `~` with the full path to the file, 2) looking out for special characters like spaces, 3) checking if the file has weird permissions, etc.

**Comment by PyPatel** [comment]
Problem is with permission. It's generated using Docker in the server where I am not an Admin. Thanks for the quick reply.

**Comment by telegraphic** [comment]
Glad you got it sorted!

**Comment by PyPatel** [comment]
I am getting following error during another run. I don't know why it is creating `NoneType` type error.

        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 624, in load
            py_container = _load(py_container, h_root_group)
          File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 756, in _load
            subdata = load_dataset(h_group)
          File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 643, in load_dataset
            py_type = h_node.attrs["type"][0]
    AttributeError: 'NoneType' object has no attribute 'attrs'
