### ISSUE TITLE
Error when installing 3.3.2

### ISSUE THREAD

**Issue by frallain** [telegraphic/hickle#89]
Hi, here is the error I get when I try to install it with python 3.6.5, pip 18.1:
```root@3b1a53a82148:/app# pip3 install hickle==3.3.2
Collecting hickle==3.3.2
  Downloading https://files.pythonhosted.org/packages/8f/b2/1371243609bcfcd27f908aaa76aa6a488d76e2fcbc3ba9dd9a85920a26ca/hickle-3.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-t0s9xn24/hickle/setup.py", line 12, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2924: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-t0s9xn24/hickle/
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
```
root@7a5f3eb876a2:/app# python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
```
```
root@3b1a53a82148:/app# pip3 -V
pip 18.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```
Any ideas?

**Comment by telegraphic** [comment]
Looks like the PyPi setup.py file is broken for Py3, I'll look into it (unsure exactly why that would be, but it looks like a classic Py2/Py3 file encoding issue).

In the meantime, could you try:
```
pip install git+https://github.com/telegraphic/hickle
```
(the github version is passing the Travis-CI tests for Python 3.6)

**Comment by telegraphic** [comment]
I've just pushed a v3.3.3, which should hopefully fix this. I think the issue was that there was a non-unicode character in the `README.md`, which was being loaded by `setup.py`. This caused Py3 to freak out. Please let me know if this fixes it

**Comment by frallain** [comment]
@telegraphic It works now, thanks!
